'use client';
import {useRef,useState,useEffect} from 'react';
import './health-research.css';
import './editorial-overrides.css';

const steps=[
 ['01','Data collection & database build','Public sources such as the WHO Global Health Expenditure Database and national datasets, followed by variable standardisation and documentation.','table'],
 ['02','Data analysis & visualisation','Cleaning, harmonising and analysing indicators before translating patterns into clear visual outputs.','visual'],
 ['03','Written synthesis','Turning evidence into concise written analysis with definitions, caveats and comparative context.','empty'],
 ['04','Report to stakeholders','Packaging findings into a structured report that supports discussion, decisions and further research.','report']
];
const rows=[['Health Insurance Type','Classification of national health insurance system (public, private, mixed)','Text'],['Average Contribution Rate','Average % of income paid as health insurance or social tax','Numeric (%)'],['Universal Health Coverage Rate','% of population with any health insurance','Numeric (%)'],['Public Insurance Coverage Rate','% of population covered by mandatory/public insurance','Numeric (%)'],['Private Insurance Coverage Rate','% of population covered by private/commercial insurance','Numeric (%)'],['Child Health Insurance Coverage','% of children covered by health insurance or government support','Numeric (%)'],['Child Co-Insurance Status','1 = children automatically covered under parents or universal scheme; 0 = separate payment required','Binary (0/1)'],['Personal Out-of-Pocket Ceiling','Maximum annual out-of-pocket payment before exemption','Numeric (USD)'],['Insurance Payout Ceiling','Maximum reimbursement limit per policy year','Numeric (USD)'],['Average Insurance Payment Ratio','% of medical costs reimbursed by insurance','Numeric (%)'],['Average Household Out-of-Pocket Ratio','Out-of-pocket spending as % of Current Health Expenditure (CHE)','Numeric (%)'],['Government Health Expenditure Ratio','GGHE/CHE – Government spending as % of total health expenditure','Numeric (%)'],['Government Subsidy for Pediatric Cancer','Fiscal support specifically for childhood cancer','Text / Binary'],['Childhood Cancer Insurance Policy','1 = dedicated insurance/fund for pediatric oncology; 0 = none','Binary (0/1)'],['National Childhood Cancer Plan – Early Screening','1 = national-level early detection strategy; 0 = none','Binary (0/1)'],['National Childhood Cancer Plan – Free Treatment','1 = national-level free treatment strategy; 0 = none','Binary (0/1)'],['Coverage of High-Cost Treatments','1 = molecular/advanced therapies covered; 0 = excluded','Binary (0/1)'],['Charitable / Social Aid for Pediatric Cancer','1 = charity/social fund participation; 0 = none','Binary (0/1)'],['Catastrophic Expenditure Rate','% of households spending >10% of annual income on child cancer treatment','Numeric (%)']];
export default function HealthResearch(){const [open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{if(open)dialog.current?.showModal()},[open]);return <div className="health-research"><div className="confidential-note"><strong>CONFIDENTIAL / ILLUSTRATIVE WORKFLOW</strong><span>All figures and examples shown here are placeholders for a confidential project, not real patient or country data.</span></div><div className="research-steps" aria-label="Research workflow">{steps.map(([n,title,copy,type])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p>{type==='table'&&<div className="step-table-hint">DATABASE SCHEMA →</div>}{type==='visual'&&<div className="step-visual-group"><img className="step-visual" src="/research/trend-analysis.png" alt="Illustrative health financing trend analysis"/><img className="step-visual" src="/research/map-analysis.png" alt="Illustrative global health financing map"/><img className="step-visual" src="/research/correlation-matrix.png" alt="Illustrative correlation matrix"/></div>}{type==='report'&&<img className="step-visual" src="/research/report-ppt.png" alt="Research report presentation overview"/>}</article>)}</div><div className="data-dictionary"><div className="table-scroll"><table><thead><tr><th>Indicator name</th><th>Description / definition</th><th>Value type</th></tr></thead><tbody>{rows.map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></div></div></div>}
