'use client';
import Communication from './Communication';
import ChapterTransition from './ChapterTransition';
import CinematicChapters from './CinematicChapters';
import HealthResearch from './HealthResearch';
import ResearchCanvas from './ResearchCanvas';
import AcademicPaper from './AcademicPaper';
import AcademicJourney from './AcademicJourney';
import InteractiveFooter from './InteractiveFooter';
import EditorialHero from './EditorialHero';
import TikTokCaseStudy from './TikTokCaseStudy';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {chapters,identities,experience,timeline,research,project,communication,assets,communicationGalleries} from '@/lib/content';
const number=(n:number)=>String(n+1).padStart(2,'0');
function Mark({n,label}:{n:string;label:string}){return <div className="section-mark"><span>{n} /</span>{label}<span className="mark-line"/></div>}
function Nav(){const [active,setActive]=useState(0);const [progress,setProgress]=useState(0);const [open,setOpen]=useState(false);const toggle=useRef<HTMLButtonElement>(null);const menu=useRef<HTMLElement>(null);useEffect(()=>{let ticking=false;const update=()=>{const sections=chapters.map(([id])=>document.getElementById(id)!);let index=0;sections.forEach((s,i)=>{if(s.getBoundingClientRect().top<=innerHeight*.38) index=i});setActive(index);setProgress(scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight));ticking=false};const scroll=()=>{if(!ticking){requestAnimationFrame(update);ticking=true}};update();addEventListener('scroll',scroll,{passive:true});return()=>removeEventListener('scroll',scroll)},[]);useEffect(()=>{if(!open)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';menu.current?.querySelector<HTMLAnchorElement>('a')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus()}if(e.key==='Tab'){const links=menu.current?.querySelectorAll<HTMLAnchorElement>('a');if(!links)return;const first=links[0],last=links[links.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};addEventListener('keydown',key);return()=>{document.body.style.overflow=old;removeEventListener('keydown',key)}},[open]);return <><header className="topbar"><a className="logo" href="#about" aria-label="Kexin Ye home">KY<span>KEXIN YE</span></a><span className="top-note">A WORK IN PROGRESS. ALWAYS.</span><button ref={toggle} className="mobile-toggle" aria-expanded={open} aria-controls="mobile-chapters" onClick={()=>setOpen(!open)}>{number(active)} / 06 · {chapters[active][1]} <span>{open?'×':'☰'}</span></button></header><nav className="chapter-nav" aria-label="Chapters"><div className="nav-count">{number(active)} <small>/ 06</small></div>{chapters.map(([id,label],i)=><a key={id} href={'#'+id} aria-current={active===i?'location':undefined}><span>{number(i)}</span>{label}</a>)}<span className="nav-caption">SCROLL TO EXPLORE</span></nav>{open&&<nav ref={menu} id="mobile-chapters" className="mobile-menu" aria-label="Mobile chapters">{chapters.map(([id,label],i)=><a key={id} href={'#'+id} onClick={()=>{setOpen(false);toggle.current?.focus()}}>{number(i)} <span>{label}</span>↗</a>)}<button onClick={()=>{setOpen(false);toggle.current?.focus()}}>Close ×</button></nav>}</>}
function Cursor(){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!matchMedia('(pointer:fine) and (hover:hover)').matches||matchMedia('(prefers-reduced-motion:reduce)').matches)return;const move=(e:PointerEvent)=>{const el=ref.current;if(!el)return;el.style.transform=`translate3d(${e.clientX}px,${e.clientY}px,0)`;const target=(e.target as HTMLElement).closest('a,button,summary');el.dataset.active=target?'true':'false';el.textContent=target?.getAttribute('data-cursor')|| (target?'VIEW':'');el.style.opacity='1'};const hide=()=>{if(ref.current)ref.current.style.opacity='0'};addEventListener('pointermove',move);document.addEventListener('pointerleave',hide);return()=>{removeEventListener('pointermove',move);document.removeEventListener('pointerleave',hide)}},[]);return <div ref={ref} className="custom-cursor" aria-hidden="true"/>}
function Hero(){return <><EditorialHero/><Timeline/></>}
function PhotoSlot({label,src}:{label:string;src?:string|null}){return <figure className={'photo-slot '+(src?'has-photo':'empty-photo')}>{src?<img src={src} alt={label} loading="lazy"/>:<div className="photo-placeholder"><span aria-hidden="true">＋</span><span>PHOTO SPACE</span><i>{label}</i></div>}<figcaption>{label}</figcaption></figure>}
function Timeline(){return <AcademicJourney/>}
function Experience(){return <TikTokCaseStudy/>}
function Research(){return <section id="research" className="research pad"><Mark n="03" label="RESEARCH"/><h2 className="display-heading research-heading">Questions worth<br/>investigating.</h2><ResearchCanvas/><article className="health-panel"><div><span className="eyebrow">01 / GLOBAL HEALTH SYSTEMS</span><h3>{research.health.title}<br/><span>{research.health.subtitle}</span></h3><p>How can health systems better protect children and families?</p><div className="health-stats">{research.health.stats.map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div></div><div className="research-index"><span className="eyebrow">LENSES OF INVESTIGATION</span>{research.health.topics.map((t,i)=><details key={t}><summary><span>{number(i)}</span>{t} ↗</summary><p>{['Examining the financial burden of care on families.','Comparing the availability and accessibility of services.','194 countries, with six comparative country deep dives.','Bringing WHO and national sources into a comparative framework.','Connecting system design with financial protection and service access.','Translating 19 indicators into clear comparisons and reporting.'][i]}</p></details>)}</div></article><AcademicPaper/></section>}
function Vibe(){const [live,setLive]=useState(false);return <section id="vibe-coding" className="vibe pad"><Mark n="04" label="VIBE CODING"/><h2 className="display-heading">IF I NEED A TOOL,<br/><span>I build one.</span></h2><div className="project-title"><div><h3>UN MONITOR<span>↗</span></h3><p>AI-powered internship aggregation platform</p></div><span className="eyebrow">INDEPENDENT DEVELOPER<br/>× PRODUCT OWNER</span></div><div className="browser-mockup reveal"><div className="browser-top"><span>● ● ●</span><span>UN MONITOR / PRODUCT PREVIEW</span><a href={project.url} target="_blank" rel="noreferrer" aria-label="Open UN Monitor">↗</a></div>{assets.monitor?<img src={assets.monitor} alt="UN Monitor job discovery dashboard" loading="lazy"/>:live?<iframe title="UN Monitor live project" src={project.url} loading="lazy"/>:<div className="product-shell"><div className="product-sidebar"><strong>UN<span>monitor</span></strong>{project.modules.map((m,i)=><span key={m}>{number(i)}　{m}</span>)}</div><div className="product-overview"><span className="eyebrow">LESS SEARCHING. MORE POSSIBILITY.</span><h4>Your next chapter,<br/><span>in one place.</span></h4><div className="product-stats">{project.stats.slice(0,3).map(([v,l])=><div key={l}><strong>{v}</strong><small>{l}</small></div>)}</div><button onClick={()=>setLive(true)} className="lime-button" data-cursor="OPEN">LOAD LIVE PROJECT ↗</button><p className="eyebrow">INTERACTIVE PREVIEW · LOADS ON REQUEST</p></div></div>}</div><div className="vibe-bottom"><strong>−70%<span>MANUAL SEARCH TIME</span></strong><div><p>Built from a repetitive problem. Shaped into a useful product.</p><div className="project-links"><a className="text-link" href={project.url} target="_blank" rel="noreferrer" data-cursor="OPEN">VIEW LIVE PROJECT ↗</a><a className="text-link" href="#build-story" onClick={()=>{const el=document.getElementById("build-story") as HTMLDetailsElement;if(el)el.open=true}}>HOW I BUILT IT ↓</a></div></div></div><details id="build-story" className="build-story"><summary>FROM 0 → 1 <span>Explore the build +</span></summary><p>AI-assisted coding with OpenAI Codex helped turn the MVP into three connected modules: job discovery, a data dashboard, and a resume workspace. Iterative validation focused on failure handling, categorization and better filters.</p><div className="process-strip">{project.pipeline.map((p,i)=><span key={p}>{i>0&&<b>→</b>}{p}</span>)}</div></details><div className="next-build"><span>NEXT BUILD ↗</span><span>COMING SOON<span className="blink">_</span></span></div></section>}
export default function Portfolio(){useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);return <><a className="skip-link" href="#main">Skip to content</a><Nav/><Cursor/><CinematicChapters/><main id="main"><section id="about"><Hero/></section><ChapterTransition number="02" label="Experience"/><Experience/><ChapterTransition number="03" label="Research"/><Research/><ChapterTransition number="04" label="Vibe Coding"/><Vibe/><ChapterTransition number="05" label="Communication"/><Communication/><ChapterTransition number="06" label="The next chapter"/><InteractiveFooter/></main></>}
