'use client';
import {useEffect,useRef} from 'react';
import './research-canvas.css';
import './research-contributions.css';
import {healthIndicators} from '@/lib/health-indicators';
export default function ResearchCanvas(){
const pin=useRef<HTMLDivElement>(null),track=useRef<HTMLDivElement>(null),viewport=useRef<HTMLDivElement>(null);
useEffect(()=>{const p=pin.current,t=track.current,v=viewport.current;if(!p||!t||!v)return;let distance=0,frame=0;
const paint=()=>{frame=0;const elapsed=Math.max(0,-p.getBoundingClientRect().top);t.style.transform='translate3d('+(-Math.min(distance,elapsed))+'px,0,0)'};
const update=()=>{if(!frame)frame=requestAnimationFrame(paint)};
const measure=()=>{v.style.setProperty('--canvas-width',v.clientWidth+'px');distance=Math.max(0,t.scrollWidth-v.clientWidth);p.style.height=(v.clientHeight+distance+120)+'px';update()};
const observer=new ResizeObserver(measure);observer.observe(v);observer.observe(t);addEventListener('scroll',update,{passive:true});addEventListener('resize',measure);measure();document.fonts.ready.then(measure);
return()=>{observer.disconnect();cancelAnimationFrame(frame);removeEventListener('scroll',update);removeEventListener('resize',measure)}},[]);
return <div ref={pin} className="research-pin"><div ref={viewport} className="canvas-viewport"><div ref={track} className="research-track">
<article className="canvas-opening"><div className="canvas-background"><span className="eyebrow">01 / GLOBAL HEALTH SYSTEMS</span><h3>GLOBAL CHILDHOOD CANCER<br/><span>Health financing</span></h3><p>How can health systems better protect children and families? Comparing health financing, insurance coverage and financial protection.</p><div className="canvas-facts"><div><strong>194</strong><span>COUNTRIES</span></div><div><strong>19</strong><span>INDICATORS</span></div><div><strong>6</strong><span>COUNTRY DEEP DIVES</span></div></div><p>Confidential project · Illustrative visuals only; displayed values are not actual research data.</p></div></article>
<article className="canvas-data"><b>01</b><h3>Data collection<br/><span>&amp; database build</span></h3><p>WHO Global Health Expenditure Database and national sources, standardised into a documented research database.</p><table className="canvas-indicators"><thead><tr><th>Indicator name</th><th>Description / definition</th><th>Value type</th></tr></thead><tbody>{healthIndicators.map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></article>
<article className="canvas-analysis canvas-contribution"><header className="contribution-heading"><b>02</b><h3>Data analysis<br/><span>&amp; visualisation</span></h3></header><div className="contribution-layout"><div className="analysis-visuals"><img src="/research/trend-analysis.png" alt="Illustrative trend analysis"/><img src="/research/map-analysis.png" alt="Illustrative global map"/><img src="/research/correlation-matrix.png" alt="Illustrative correlation matrix"/></div><div className="contribution-copy"><div><h4>Data cleaning &amp; modelling</h4><p>I harmonised health expenditure and insurance coverage definitions across countries, then cleaned and structured multi-source panel data.</p></div><div><h4>Multidimensional analysis</h4><p>I built a quantitative indicator framework and ran correlation and trend models to investigate links between out-of-pocket spending and financial protection.</p></div><div><h4>From evidence to insight</h4><p>I translated statistical results into country trends, global spatial comparisons and correlation matrices, drawing out policy-relevant insights.</p></div></div></div></article>
<article className="canvas-written"><b>03</b><h3>Country deep dives<br/><span>&amp; findings</span></h3></article><article className="canvas-report canvas-contribution"><header className="contribution-heading"><b>04</b><h3>Report<br/><span>to stakeholders</span></h3></header><div className="contribution-layout"><div className="report-visual"><img src="/research/report-ppt.png" alt="Complete research report slide overview"/></div><div className="contribution-copy"><div><h4>Stakeholder reporting</h4><p>I brought the empirical findings together into a complete presentation for experts and decision-makers.</p></div><div><h4>Policy recommendations</h4><p>I developed actionable recommendations addressing inequalities in healthcare financing and high out-of-pocket burdens across countries.</p></div><div><h4>Research synthesis &amp; delivery</h4><p>I delivered an integrated report connecting the research background and indicator framework with empirical analysis and strategic insights.</p></div></div></div></article></div></div></div>}
